DROP DATABASE IF EXISTS gaestebuch;
CREATE DATABASE gaestebuch; 
USE gaestebuch;
DROP TABLE IF EXISTS eintrag;
CREATE TABLE eintrag(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    datum DATE,
    ueberschrift VARCHAR(40) NOT NULL,
    text VARCHAR(125) NOT NULL
) ENGINE = InnoDB;

